name: update cmd
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches:
      - master

jobs:
  build-and-update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14"
      - run: go version
      - name: build
        run: |
          bin/build
      - name: push current changes
        run: |
          if [[ -z $(git status -s) ]]
          then
            git config --global user.email "action@github.com"
            git config --global user.name "github-actions[bot]"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
            git push origin HEAD
          fi
