name: monthly trending update
on:
  schedule:
    - cron: "0 11 1 * *"

jobs:
  fetch-and-update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: set environment variable
        run: |
          echo ::set-env name=update_branch::monthly-$(date +%F)
          echo ::set-env name=pr_title::"Monthly update "$(date +%F)
      - name: update
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b ${{ env.update_branch }}
          ./update monthly
          git add src/
          git commit -m "monthly update "$(date +%F)
      - name: push current changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.update_branch }}
      - uses: actions/checkout@v1
      - name: create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.update_branch }} # If blank, default: triggered branch
          destination_branch: "master" # If blank, default: master
          pr_title: ${{ env.pr_title }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
