name: weekly trending update
on:
  schedule:
    - cron: "0 12 * * MON"
  workflow_dispatch:

jobs:
  fetch-and-update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: set environment variable
        run: |
          echo ::set-env name=update_branch::weekly-$(date +%F)
          echo ::set-env name=pr_title::"Weekly update "$(date +%F)
      - name: update
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b ${{ env.update_branch }}
          yarn
          yarn scrape weekly
          ./main weekly
          git add src/
          git commit -m "weekly update "$(date +%F)
      - name: push current changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.update_branch }}
      - uses: actions/checkout@v1
      - name: create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.update_branch }} # If blank, default: triggered branch
          destination_branch: "main" # If blank, default: master
          pr_title: ${{ env.pr_title }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
